spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: workflow_db
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus